# Generated by Django 3.2.9 on 2022-02-08 05:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_customuser_email_corp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formsmaws',
            options={'verbose_name': 'Черновики МАФС', 'verbose_name_plural': 'Черновики МАФС'},
        ),
        migrations.AddField(
            model_name='formsmaws',
            name='date',
            field=models.CharField(default='', max_length=250, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='formsmaws',
            name='location',
            field=models.CharField(default='', max_length=250, verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='formsmaws',
            name='manager',
            field=models.CharField(default='', max_length=250, verbose_name='Менеджер склада'),
        ),
        migrations.AddField(
            model_name='formsmaws',
            name='placement',
            field=models.CharField(default='', max_length=250, verbose_name='Помещение'),
        ),
        migrations.AddField(
            model_name='formsmaws',
            name='storage',
            field=models.CharField(default='', max_length=250, verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='loglist',
            name='description',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Описание/Номер'),
        ),
        migrations.AddField(
            model_name='loglist',
            name='tag',
            field=models.CharField(default='', max_length=250, verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='vacations',
            name='line_manager',
            field=models.CharField(default='', max_length=250, verbose_name='Line Manager'),
        ),
        migrations.AlterField(
            model_name='formsmaws',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='loglist',
            name='doc_date',
            field=models.DateTimeField(null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='loglist',
            name='full_name',
            field=models.CharField(default='', max_length=250, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='vacations',
            name='doc_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='vacations',
            name='full_name',
            field=models.CharField(default='', max_length=250, verbose_name='Организация'),
        ),
    ]
