# Generated by Django 3.2.9 on 2022-02-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20220208_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loglist',
            name='full_name',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='vacations',
            name='full_name',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Организация'),
        ),
    ]
