# Generated by Django 3.2.9 on 2022-02-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20220209_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacations',
            name='line_manager',
            field=models.CharField(default='-', max_length=250, verbose_name='Line Manager'),
        ),
    ]
