# Generated by Django 3.2.9 on 2022-02-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20220209_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loglist',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='vacations',
            name='full_name',
        ),
        migrations.AddField(
            model_name='loglist',
            name='decree',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Приказ'),
        ),
        migrations.AddField(
            model_name='vacations',
            name='decree',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Приказ'),
        ),
        migrations.AddField(
            model_name='vacations',
            name='description',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Описание/Номер'),
        ),
        migrations.AlterField(
            model_name='loglist',
            name='description',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Описание/Номер'),
        ),
        migrations.AlterField(
            model_name='vacations',
            name='line_manager',
            field=models.CharField(default='', max_length=250, verbose_name='Line Manager'),
        ),
    ]
